### ISSUE TITLE
[Feat] 에러 핸들링

### ISSUE THREAD

**Issue by Heo-Donghyuk** [Step3-kakao-tech-campus/Team3_FE#103]
# 기능 이슈

## Description

에러 핸들링
error.tsx, toast를 이용한 api 예외 처리

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요

- [x] 전역 error.tsx 적용( + 전역 loading.tsx)
- [x] GET 메소드 (페이지) 예외 처리 (useErrorBoundary or suspense)
- [x] 모달 단위 에러바운더리 처리
- [x] POST, PUT, PATCH, DELETE 등 mutate 예외처리 (api 분류 별)
