### ISSUE TITLE
[Feat] 모바일 UI 남은부분 구현

### ISSUE THREAD

**Issue by kjh302903** [Step3-kakao-tech-campus/Team3_FE#107]
# 기능 이슈

## Description

> 모바일 UI 남은부분 구현

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요

- [x] 대화 페이지 모바일 UI
- [x] 이미지 모달 모바일 UI
- [x] 별점 모달 모바일 UI
- [x] 점수 입력 모달 모바일 UI
- [x] 스코어보드 페이지 모바일 UI
