### ISSUE TITLE
[Feat] 메인 페이지 기능 개발

### ISSUE THREAD

**Issue by Heo-Donghyuk** [Step3-kakao-tech-campus/Team3_FE#12]
# 기능 이슈

## Description

> 메인 페이지에서 이용되는 다양한 기능을 개발한다
<br>

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요
- [x] 드롭다운 박스 로직 수정
- [x] 지역 검색 바 구현
- [x] 전체 보기, 모집중 선택 버튼 구현
- [x] 글쓰기 버튼 구현
- [x] 현재 검색된 지역 표기 컴포넌트 구현
- [x] 인피니티 스크롤 적용
<br>
