### ISSUE TITLE
[Feat] 모집글 카드 컴포넌트(PostCard) 제작

### ISSUE THREAD

**Issue by Heo-Donghyuk** [Step3-kakao-tech-campus/Team3_FE#2]
# 기능 이슈

## Description

> 메인 페이지에 보일 모집글 카드 컴포넌트 UI 제작
<br>

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요
- [x] Badge 컴포넌트 제작 - atom
- [x] 컴포넌트 UI 제작
- [x] 더미 데이터 활용하여 리팩토링
---
> 추가 작업 내역
- [x] PostCard prop 객체화
- [x] hover시 scale(103%) 효과 적용
- [x] Image 컴포넌트로 기본 이미지 적용
- [x] Link 적용
<br>

**Comment by Heo-Donghyuk** [comment]
<img width="897" alt="image" src="https://github.com/Step3-kakao-tech-campus/Team3_FE/assets/137741073/37974615-711c-4f5c-af0e-bcd163dc5f44">

- Link의 href는 현재 /post/[postid]로 설정되어 있다. 추후 세그먼트 확정시 수정이 필요할 수 있다.
- 프로필 이미지가 기본이 아닌 경우, API URL과 이미지 비율에 대해 수정할 필요가 있다.
- 작성자 프로필을 클릭하여 모달을 띄우는 기능은 현재 구현되어 있지 않다.
