### ISSUE TITLE
[Feat] 회원가입 UI 제작

### ISSUE THREAD

**Issue by Jiho-Park-0** [Step3-kakao-tech-campus/Team3_FE#3]
# 기능 이슈

## Description

> 회원가입 모달 UI 제작
<br>

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요
- [x] input 컴포넌트 UI 제작
- [x] checkbox 컴포넌트 UI 제작
- [x] button 컴포넌트 UI 제작
- [x] dropdown 컴포넌트 UI 제작
<br>

**Comment by Jiho-Park-0** [comment]
![image](https://github.com/Step3-kakao-tech-campus/Team3_FE/assets/79912184/74378833-6c39-4210-8752-fafe90a0627d)
