### ISSUE TITLE
[Feat] 신청자 확인 모달 구현

### ISSUE THREAD

**Issue by Heo-Donghyuk** [Step3-kakao-tech-campus/Team3_FE#30]
# 기능 이슈

## Description

> 신청자 확인 모달과 이용 되는 기능을 구현한다.
> <br>

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요

- [x] 신청자 확인 모달 UI 구현
- [x] 각 신청자 별 출력 컴포넌트 구현 - ApplicantBlock
- [x] 신청자 조회 기능 구현
- [x] 수락 / 거절 기능 구현
- [x] 마감하기 기능 구현 - 추후 api 구현 완료 시 진행 예정
      <br>
