### ISSUE TITLE
[Feat] 참여기록 페이지 UI 구현

### ISSUE THREAD

**Issue by Heo-Donghyuk** [Step3-kakao-tech-campus/Team3_FE#40]
# 기능 이슈

## Description

> 참여기록 페이지 UI를 구현한다.
> <br>

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요

- [x] 모든 경기에 대한 요약을 제공하는 RecordSummary 제작
- [x] 검색된 참여기록을 분류하는 RecordFilter 제작
- [x] 참여기록을 검색하는 RecordSearchBar 제작
- [x] 하나의 참여 기록을 표현할 RecordCard 제작
      <br>
