### ISSUE TITLE
[Feat] 게시글의 신청 / 취소 / 신청자 확인 기능 구현

### ISSUE THREAD

**Issue by kjh302903** [Step3-kakao-tech-campus/Team3_FE#48]
# 기능 이슈

## Description

> 게시글의 신청 / 취소 / 신청자 확인 기능을 구현한다.

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요

- [x] 게시글 신청 기능
- [x] 게시글 취소 기능
- [x] 신청자 확인 기능
      <br>
