### ISSUE TITLE
[Feat] NavigationBar UI 제작 

### ISSUE THREAD

**Issue by kjh302903** [Step3-kakao-tech-campus/Team3_FE#5]
# 기능 이슈

## Description

> GlobalNavigationBar UI를 개발
<br>

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요
- [x] InnerContainer 컴포넌트 제작
- [x] Button 컴포넌트 제작
- [x] NavigationBar UI 완성
<br>
