### ISSUE TITLE
[Feat] 참여 기록 페이지 기능 구현

### ISSUE THREAD

**Issue by Heo-Donghyuk** [Step3-kakao-tech-campus/Team3_FE#56]
# 기능 이슈

## Description

> 기능에 대해 설명해주세요
참여 기록 페이지 기능 구현

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요

- [x] RecordFilter 기능 구현
- [x] RecordSearchBar 기능 구현
- [x] RecordCardList 기능 구현
- [x] RecordCard 기능 구현
      <br>
