### ISSUE TITLE
[Feat] 점수 등록, 수정, 별점 등록 기능 구현

### ISSUE THREAD

**Issue by Heo-Donghyuk** [Step3-kakao-tech-campus/Team3_FE#58]
# 기능 이슈

## Description

> 기능에 대해 설명해주세요
스코어 보드 페이지의 점수 등록, 수정, 별점 등록 기능 구현 

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요
 - [x] 점수 등록 모달 UI 구현
 - [x] 점수 수정 로직 구현
 - [x] 점수 등록 및 수정 api 적용
 - [x] 별점주기 모달 UI 구현
 - [x] 별점주기 api 적용
