### ISSUE TITLE
[Refactor] 기존의 라우팅 모달 변경

### ISSUE THREAD

**Issue by kjh302903** [Step3-kakao-tech-campus/Team3_FE#73]
# 기능 이슈

## Description

> 기존의 프로필 모달, 신청자 확인 모달을 라우팅 방식으로 띄우는 것에서 state로 컴포넌트 띄우는 방식으로 변경

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요

- [x] 기존의 프로필 모달 삭제
- [x] 기존의 신청자 확인 모달 삭제
- [x] 프로필 모달 재 구현
- [x] 신청자 확인 모달 재 구현
- [x] 모달 띄우고 없애는 부분 로직 수정
