### ISSUE TITLE
[Fix] Badge 마감 판단 로직 수정 및 점수, 별점 등록 버튼 표현 로직 수정

### ISSUE THREAD

**Issue by Heo-Donghyuk** [Step3-kakao-tech-campus/Team3_FE#87]
# 기능 이슈

## Description

Badge 마감 판단 로직 수정 및 점수, 별점 등록 버튼 표현 로직 수정

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요

- [x] Badge 마감 판단 로직 수정
- [x] '마감하기'버튼 '모집완료'로 수정
- [x] 점수, 별점 등록 버튼 표현 로직 수정
