### ISSUE TITLE
[Feat] 모바일 UI 개발

### ISSUE THREAD

**Issue by kjh302903** [Step3-kakao-tech-campus/Team3_FE#98]
# 기능 이슈

## Description

> 메인페이지 모바일 UI 개발

## To-do

> 전체적인 각 할일 분배에 대해 설명해주세요

- [x] 메인페이지 모바일 UI 
- [x] GNB 모바일 UI 
- [x] 로그인 모달 모바일 UI
- [x] 회원가입 모달 모바일 UI
- [x] Create 페이지 모바일 UI
- [x] 게시글 페이지 모바일 UI
- [x] 신청자 확인 모달 모바일 UI
- [x] 프로필 모달 모바일 UI 
- [x] 토스트 모바일 UI 
- [x] 게시글 수정 페이지 모바일 UI
- [x] 삭제 모달 모바일 UI
- [x] 볼링장 찾기 페이지 모바일 UI
- [x] 마이페이지 모바일 UI
- [x] 사용자 검색 모달 모바일 UI
- [x] 쪽지함 페이지 모바일 UI 
      <br>
